version: '3.8'

services:
    graphql-backend:
        container_name: graphql-backend
        depends_on:
            - graphql-mysql
        build: ./docker
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:8000
            
    graphql-mysql:
        container_name: graphql-mysql
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/init_scripts/:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    graphql-phpmyadmin:
        container_name: graphql-phpmyadmin
        depends_on:
            - graphql-mysql
        image: phpmyadmin
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=graphql-mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=${DB_PASSWORD}
            - UPLOAD_LIMIT=50M